/// Canonical AI gateway interface. All model providers implement this.
/// See PROMPT.md §3 and BLUEPRINT.md §2.1.
library;

import '../../models/task.dart';

/// Snapshot of user data injected into model prompts.
class TaskContext {
  TaskContext({this.openTaskCount = 0, this.todayTaskCount = 0});

  final int openTaskCount;
  final int todayTaskCount;
}

/// Streaming chat chunk from the gateway.
class ChatChunk {
  ChatChunk({required this.text, this.done = false});

  final String text;
  final bool done;
}

/// Explanation for why a task got its priority ranking.
class PriorityRationale {
  PriorityRationale({required this.taskId, required this.rationale});

  final String taskId;
  final String rationale;
}

/// End-of-day review generated by the model.
class DailyReview {
  DailyReview({
    required this.wins,
    required this.misses,
    required this.tomorrowTopThree,
  });

  final List<String> wins;
  final List<String> misses;
  final List<String> tomorrowTopThree;
}

/// Configuration for a provider (base URL, key, model names).
class AiConfig {
  AiConfig({
    required this.baseUrl,
    required this.apiKey,
    this.chatModel = 'gpt-4o-mini',
    this.parseModel = 'gpt-4o-mini',
  });

  final String baseUrl;
  final String apiKey;
  final String chatModel;
  final String parseModel;
}

/// Provider-agnostic AI gateway. Implementations must validate model
/// output before returning; UI never calls provider SDKs directly.
abstract interface class AiGateway {
  /// Parse natural language into a structured task draft.
  Future<TaskDraft> parseTask(String input);

  /// Decompose a task into ordered subtasks.
  Future<List<SubtaskDraft>> generateSubtasks(Task task);

  /// Explain why a task holds its current priority ranking.
  Future<PriorityRationale> explainPriority(Task task, TaskContext ctx);

  /// Streaming chat with the Day Pilot assistant.
  Stream<ChatChunk> chat(List<ChatMessage> history, TaskContext ctx);

  /// Generate the end-of-day review.
  Future<DailyReview> dailyReview(DayLog log);
}

/// Summary of a day's activity for review generation.
class DayLog {
  DayLog({required this.completedTitles, required this.openTitles});

  final List<String> completedTitles;
  final List<String> openTitles;
}

/// Failure modes surfaced uniformly across providers.
sealed class AiException implements Exception {
  const AiException(this.message);

  final String message;

  @override
  String toString() => '$runtimeType: $message';
}

class AiNetworkException extends AiException {
  const AiNetworkException(super.message);
}

class AiParseException extends AiException {
  const AiParseException(super.message);
}
